# Generated by Django 3.2.4 on 2021-06-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_post_lokes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lokes',
            new_name='likes',
        ),
    ]
